---

- name: Deploy logrotate configuration
  ansible.builtin.template:
    src: templates/renderd.j2
    dest: /etc/logrotate.d/renderd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Delete update-tiles logs older than 7 days
  ansible.builtin.cron:
    name: "delete update-tiles logs older than 7 days"
    minute: "0"
    hour: "2"
    job: "find {{ update_logs_dir }}/osm2pgsql-replication.* -mtime +7 -exec rm {} \\;"
  become: true
