---

- name: Deploy webpage
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: "{{ html_dir }}/index.html"
    owner: "{{ renderd_user }}"
    group: "{{ renderd_user }}"
    mode: '0644'
  become: true
